### ISSUE TITLE
[Feature Request] Decrypt Passwords in ENV var's

### ISSUE THREAD

**Issue by jdoubleu** [siomiz/SoftEtherVPN#11]
It would be nice if there's an option to decrypt the passwords given to the `-e PASSWORD` or `-e USERS` vars.

Due to the fact that the `vpncmd` (or the `UserSetPassword` command) only accepts plaintext passwords it would be a nice feature to encrypt a password (e.g. using rsa) and the container decrypts it internal and uses it for the `vpncmd`.

Yet the password may be visible in process list or in docker-compose files.

**Comment by siomiz** [comment]
Hi @jdoubleu 

You can either:

- [Use `--env-file` argument](https://docs.docker.com/engine/reference/commandline/run/#/set-environment-variables-e-env-env-file) ([`env_file` in compose file](https://docs.docker.com/compose/compose-file/#/env-file)) to keep credentials in a separate file (but note that env vars will still show up in `docker inspect`), or
- Mount the SoftEther VPN config file (which includes hashed ("encrypted") passwords) at `/opt/vpn_server.config`. [Initial setup will be skipped if this file exists at runtime](https://github.com/siomiz/SoftEtherVPN/blob/1065fe4693c67b5e34954442236eb8152142e64a/copyables/entrypoint.sh#L11). You can obtain this file from a running container using [`docker cp` command](https://docs.docker.com/engine/reference/commandline/cp/).

Hope this helps!

**Comment by jdoubleu** [comment]
Oh okay, thanks!

This was what I looked for!

Maybe you mention it in the `README.md`?

Can be closed.
