### ISSUE TITLE
how to mount vpn_server.config

### ISSUE THREAD

**Issue by lodgnewt** [siomiz/SoftEtherVPN#21]
please help me start docker container with my vpn_server.config (copied from the configured container)

how to run the container that it runs with the configuration file and run if the server is rebooted?
I think so: 
`docker run -d --cap-add NET_ADMIN --name vpn --restart always -v /vpn_server.config:/opt/vpn_server.config siomiz/softethervpn`

 but the configuration does not work.

**Comment by siomiz** [comment]
That seems to be the correct syntax, provided the file exists at `/`.

> the configuration does not work

Does the config file being mounted actually contain your config?
It's a text-based file so you can read (_or modify_) on host easily. Please double-check.

is any config edited after the server started?
If the server is not gracefully shutting down, you may need to issue `Flush` command in the server console (it should be automatically happening every 5 minutes) after config changes.
See https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.3_VPN_Server_%2F%2F_VPN_Bridge_Management_Command_Reference_(For_Entire_Server)
