### ISSUE TITLE
L2TP seems not working

### ISSUE THREAD

**Issue by paolomainardi** [siomiz/SoftEtherVPN#22]
Hello, as in the subject seems that L2TP connection is not working as expected:

```
~ ❯ docker run -d --privileged --cap-add NET_ADMIN -p 500:500/udp -p 4500:4500/udp -p 1701:1701/tcp -p 1194:1194/udp -p 5555:5555/tcp siomiz/softethervpn
658f576bb603cd08a7fff25dc317f42142cc1ee787becc7a7c6f5198c2a3a74f
~ ❯ docker ps | grep 658f576b
658f576bb603        siomiz/softethervpn                        "/entrypoint.sh /u..."   9 seconds ago       Up 8 seconds        0.0.0.0:500->500/udp, 0.0.0.0:1194->1194/udp, 0.0.0.0:1701->1701/tcp, 0.0.0.0:4500->4500/udp, 0.0.0.0:5555->5555/tcp   gallant_ptolemy

~ ❯ telnet 192.168.99.100 1701 <<< --- NOT WORKING
Trying 192.168.99.100...
telnet: connect to address 192.168.99.100: Connection refused
telnet: Unable to connect to remote host



~ ❯ telnet 192.168.99.100 5555                                                                                                                                      ⏎
Trying 192.168.99.100...
Connected to dockerdev.
Escape character is '^]'.

ˆCTRL-C
Connection closed by foreign host.
```

OS: ~ ❯ Darwin paolospark 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64

~ ❯ docker --version
Docker version 1.13.0, build 49bf474

~ ❯ docker-machine ip dinghy
192.168.99.100

Thanks!

**Comment by siomiz** [comment]
The port 1701 is supposed to be used for UDP ("optionally" exposed), so telnet (TCP) can't talk to it.
https://en.wikipedia.org/wiki/Layer_2_Tunneling_Protocol#L2TP.2FIPsec

Though I had a problem with an iOS VPN client not being able to connect to the container if it's not exposing 1701/tcp. ([relevant commit](https://github.com/siomiz/SoftEtherVPN/commit/5c5b0f1ca4a2417ae7148bd28ff4fcd5ebe16530))
