### ISSUE TITLE
q: is there a way to enable split tunneling

### ISSUE THREAD

**Issue by LorenzoBoccaccia** [siomiz/SoftEtherVPN#26]
I'm trying to use this vpn to connect to my docker network without having to expose every port to the internet

it works well, but every bit of traffic is routed trough the vps trough the vpn, and it's burning the vps bandwidth and making everything slower.

is there a way to configure split tunneling on the image? I've tried changing the metric or the default gateway, but so far it's either everything gets tunneled or nothing

**Comment by siomiz** [comment]
https://mpxxuk.wordpress.com/2015/12/12/softether-splitting-vpn-traffic/
says the DHCP server can push the routes down to client.
(it would require the hub management password `-e HPW`)

or you can split traffic on the client side, ex. if you're using OpenVPN client:
https://support.vpnsecure.me/articles/frequently-asked-questions/openvpn-split-tunneling

Not sure of your setup but I'd suggest [the Docker Swarm mode](https://docs.docker.com/engine/swarm/) with [secure overlay networking](https://docs.docker.com/engine/userguide/networking/overlay-security-model/) for a multi-host solution.
