### ISSUE TITLE
Using OPENVPN over HTTPS simultaneously with NGINX?

### ISSUE THREAD

**Issue by clobber88** [siomiz/SoftEtherVPN#27]
I'm running a handful of containers using nginx-proxy and its companion (to get LetsEncrypt certs). Anyway, this configuration means my server is already listening on port 443 and farming out requests to the various backends.

I would also like to be able to use SoftEther over port 443 as well. 

Is there a way to do this?

**Comment by siomiz** [comment]
You probably want [sslh](https://github.com/yrutschle/sslh) as a frontend for both nginx and softethervpn.
