### ISSUE TITLE
RMD160 isn't available in the docker container

### ISSUE THREAD

**Issue by datenzar** [siomiz/SoftEtherVPN#28]
When trying to log into the VPN server from Windows client, I get the message `hash algorithm 'RMD160' not found`

Same for iOS devices where the error says `crypto_alg: RMD160: not found`

The host runnnig the containers has RIPEMD160 installed (tested via `openssl rmd160 /usr/bin/openssl`)

**Comment by siomiz** [comment]
Strange, the [SoftEther VPN Spec](https://www.softether.org/3-spec) says RMD160 is supported as an OpenVPN auth digest.

Unfortunately I don't have the time to investigate this right now...
You can edit the line `auth RMD160` in your .ovpn file to `auth SHA1`, for example, to mitigate.

This image does not utilize host's OpenSSL library.

**Comment by datenzar** [comment]
Thanks for closing (though intentionally)! I actually didn't follow your suggestion but instead also removed the patch ;-)
