### ISSUE TITLE
seems to have memory leak problem

### ISSUE THREAD

**Issue by tzwm** [siomiz/SoftEtherVPN#36]
I deployed the latest image and found memory leaks.
And I restart the container so memory have been reduced.

![image](https://user-images.githubusercontent.com/828837/33644192-44abd1e2-da7e-11e7-9f11-d729da19dbfd.png)

**Comment by siomiz** [comment]
You may want to
- try **:9651** tag; **:latest** uses v4.22-9634-beta due to compatibility issues (#33) 
  - if this "leak" still persists, file an issue at [SoftEtherVPN/SoftEtherVPN](https://github.com/SoftEtherVPN/SoftEtherVPN); this image is only a wrapper for it.

**Comment by tzwm** [comment]
I will try :9651 tag, thx.
