### ISSUE TITLE
Virtual Hubs disappear after container restarts

### ISSUE THREAD

**Issue by darkson95** [siomiz/SoftEtherVPN#38]
I use this docker container on my Synology and after a container restart, all the virtual hubs disappear and the settings are set to default. Is there any possibility to save the virtual hub configuration?
Thanks

**Comment by siomiz** [comment]
All configuration is written to `/opt/vpn_server.config` file inside the container,
so you can mount it from host to make it survive across container restarts.
`docker run -v /path/on/host/vpn_server.config:/opt/vpn_server.config ... siomiz/softethervpn`

**Comment by darkson95** [comment]
The problem was that the VPN Server Manager did not save the config file because he did not have enough permissions. I copied the config file manually and now it works. 
Thanks a lot! :)
