### ISSUE TITLE
OpenVPN loses connection, Authenticate/Decrypt packet error: missing payload

### ISSUE THREAD

**Issue by eciuca** [siomiz/SoftEtherVPN#42]
Hi, I found this (https://github.com/SoftEtherVPN/SoftEtherVPN/issues/434) issue on the SoftEtherVPN repo that affects your Docker image since you updated it from centos to debian (https://github.com/siomiz/SoftEtherVPN/commit/68ffa3420a8667f2a99cf84cbc81232228ee3d3b).

Can you please solve it, I am not sure if I have time.

Also, can you tag versions so you have 1 docker image for every SoftEtherVPN version you build? I had to clone the repo and build the image myself :(

My use case is that I have a vpn server on AWS and when I restart the server it downloads the 'latest' tag because it is the only one you build so I get updates automatically which could break my server.

**Comment by siomiz** [comment]
I hear you. Let me come up with a game plan tomorrow...

**Comment by siomiz** [comment]
Ok I went ahead with the plan to maintain many tags. Also made `:latest` back to CentOS-based.
Please refer to [README.md](https://github.com/siomiz/SoftEtherVPN/blob/9656/README.md) for the list of available Docker image tags. I'm still cleaning up things but all tags are stable enough.

**Comment by davidebeatrici** [comment]
Hi, I found out the cause of the issue and posted a temporary workaround for Debian Stretch: https://github.com/SoftEtherVPN/SoftEtherVPN/issues/434#issuecomment-381358311.

**Comment by siomiz** [comment]
@davidebeatrici Thank you for the workaround! I have incorporated it into `:debian` tag.

**Comment by davidebeatrici** [comment]
@siomiz You're welcome!
