### ISSUE TITLE
Env var for remote parameter

### ISSUE THREAD

**Issue by rgarrigue** [siomiz/SoftEtherVPN#49]
Hello,

Here a piece of config found in the docker log output

```
softether_1      | # ========================
softether_1      | # <use the password specified at -e USERS>
softether_1      | # SecureNat MTU set to 1500
softether_1      | # ========================
softether_1      | # Version 4.25 Build 9656   (English)
softether_1      | dev tun
softether_1      | proto udp
softether_1      | remote vpn706636462.v4.softether.net 1194
softether_1      | ;http-proxy-retry
softether_1      | ;http-proxy [proxy server] [proxy port]
softether_1      | cipher AES-128-CBC
softether_1      | auth SHA1
softether_1      | resolv-retry infinite
softether_1      | nobind
softether_1      | persist-key
softether_1      | persist-tun
```

This `remote vpn706636462.v4.softether.net 1194` seems hardcoded. I know that's just some help and one should know how to fix that, but allowing one to set this up via environment var would be more user friendly.

Best regards,

**Comment by siomiz** [comment]
No, it is assigned by [SoftEther VPN's Dynamic DNS](https://www.softether.org/4-docs/2-howto/6.VPN_Server_Behind_NAT_or_Firewall/1.Dynamic_DNS_and_NAT_Traversal), so it should be pointing to your Docker host's public IP address when the config is created.
You can change its behavior by modifying the `/opt/vpn_server.config` or run the [`DynamicDnsSetHostname` server command](https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.3_VPN_Server_%2F%2F_VPN_Bridge_Management_Command_Reference_(For_Entire_Server)#6.3.83_.22DynamicDnsSetHostname.22:_Set_the_Dynamic_DNS_Hostname).

**Comment by rgarrigue** [comment]
Ok, thanks for the intel.

I wish I could have a docker-compose.yml setting up a VPN entirely; without going for "start a first softether container, copy vpn_server.config, customize it, mount this file in the second final container defined in docker-compose.yml". 

I mean, i'm don't know much about VPNs, I just wish to input users & passwords, maybe a couple of settings like hostname & ports and be done with it, no fight with certificate, MTU etc.

Do you see a way to do that ? 

Best regards,

**Comment by siomiz** [comment]
Refer to [Credentials section of `README.md`](https://github.com/siomiz/SoftEtherVPN/blob/master/README.md#credentials) for users & passwords (`-e USERS`).
Exposed ports you can control with `-p` or in your `docker-compose.yml` (or _change_ if you _really_ need to).
I still don't see a case where you have to specify hostname on the server side... please enlighten me with some examples?
