### ISSUE TITLE
VPN configuration is lost each time running container is restarted

### ISSUE THREAD

**Issue by nrjohnstone** [siomiz/SoftEtherVPN#56]
Given that I have configured my VPN container and it is running with the name of "vpn" if I do

sudo docker stop vpn
sudo docker start vpn

I lose all the settings and configured users as if it was starting again for the first time

**Comment by nrjohnstone** [comment]
It seems to be related to the permissions that the vpnserver runs under due to the command "vpnserver execsvc" as this does not appear to have write access to /opt/vpn_server.config

If you start the container any bypass the entry point and then use "vpnserver start" the config is updated correctly and is persistent across restarts of the service.

**Comment by nrjohnstone** [comment]
Figured out what the issue is, by default the configuration file only gets saved to disk every 300 seconds... so before copying the configuration out of the docker container you just need to wait for it to be saved to disk.

Or, attach to the server using the UI tool, and save the configuration file from memory to disk directly and then use that one.

**Comment by siomiz** [comment]
Thank you for the report; I will update the README to include the link to the [server admin doc](https://www.softether.org/4-docs/1-manual/3._SoftEther_VPN_Server_Manual/3.3_VPN_Server_Administration) where (inconspicuously) mentions the 300-sec auto config save cycle.
