### ISSUE TITLE
Multiple user not supported?

### ISSUE THREAD

**Issue by hyp530** [siomiz/SoftEtherVPN#6]
Hi. Why multiple users  is not supported?

**Comment by siomiz** [comment]
I simply wanted a zero-configuration image that just works for my needs.

You can tweak the "server lock-down" part in [entrypoint.sh](https://github.com/siomiz/SoftEtherVPN/blob/master/copyables/entrypoint.sh) (maybe echo the hub/server passwords out?).
I'm sure somebody already has an image/fork which does exactly that...

**Comment by hyp530** [comment]
Thank you very much for your reply. I will have a try.
