### ISSUE TITLE
How to define -e HPW in docker-compose file

### ISSUE THREAD

**Issue by kamalpanhwar** [siomiz/SoftEtherVPN#66]
I am using this Dockerfile in docker-compose.yml but how do I define passwords in this file or Dockerfile, so I can access server programmatically.

**Comment by siomiz** [comment]
Refer to the official Compose file spec:
https://docs.docker.com/compose/compose-file/#environment

**Comment by kamalpanhwar** [comment]
Great, I added following lines in my docker-compose.yml file and it work
```yml
environment:
   SPW:yourpassword
   HPW:yourpassword
```
Thanks.
