### ISSUE TITLE
Update readme with example on how to customize the DNS

### ISSUE THREAD

**Issue by diwu1989** [siomiz/SoftEtherVPN#77]
It's not clear which DNS server is being used by default.

Can we add a snippet to the ReadMe for how to set an alternative DNS?
My use-case is I would like to have the VPN use AdguardDNS
https://adguard.com/en/adguard-dns/overview.html#instruction

**Comment by siomiz** [comment]
I won't provide support on general usage of SoftEther VPN.

Specify Server Password (`SPW`) and Hub Password (`HPW`) then refer to the [Server Administration manual](https://www.softether.org/4-docs/1-manual/3._SoftEther_VPN_Server_Manual/3.3_VPN_Server_Administration).
