### ISSUE TITLE
Error in log: can't initialize iptables table `filter'

### ISSUE THREAD

**Issue by nOrphf** [siomiz/SoftEtherVPN#80]
Hi

Running you awesome image on my Synology, but keeps getting the following error in the log:

iptables v1.4.21: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

I that because I need to activate "Execute the container using high privileges" ?

Regards Lars

**Comment by siomiz** [comment]
As your error log should also state:
[`# [!!] This image requires --cap-add NET_ADMIN`](https://github.com/siomiz/SoftEtherVPN/blob/master/copyables/entrypoint.sh#L16)

Give it the `NET_ADMIN` capability or run as root/privileged if your particular environment doesn't allow you to fine-tune the Linux capabilities for Docker (probably the case for Synology).

**Comment by luthfi-hh** [comment]
@siomiz If I remove the `iptables` package from the Dockerfile, will SoftEther still work?
