### ISSUE TITLE
[Request] Update Server to SoftEther VPN 4.34 Build 9745 RTM

### ISSUE THREAD

**Issue by radioactivetoy** [siomiz/SoftEtherVPN#83]
As 4.34 has been released as RTM non beta, coould it be possible to update the server to this version?

**Comment by siomiz** [comment]
Hmm... they might've relabeled it as a beta?
https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/tag/v4.34-9745-beta

I'll try to create new images based on it anyway.

**Comment by siomiz** [comment]
Ok I have pushed manually-built images from `9745` branch as tags:
`9745`/`9745-centos`, `9745-alpine`, `9745-debian`, and `9745-ubuntu`.
(see https://hub.docker.com/r/siomiz/softethervpn/tags?name=9745)
[They passed simple tests](https://github.com/siomiz/SoftEtherVPN/actions/runs/159936253) but may be broken.

I'll pull in https://github.com/siomiz/SoftEtherVPN/pull/84 later with properly updated README and such...

**Comment by amonhk** [comment]
> Hmm... they might've relabeled it as a beta?

this is not very clear, in changelog they write:

> SoftEther VPN 4.34 Build 9745 RTM (June 24, 2020)
> 
> All cumulative updates bellow are included.
> Build 9745 beta is determined to be stable enough and is remarked as RTM.
> The contents of the packages are exactly the same as Build 9745 beta.

**Comment by radioactivetoy** [comment]
I understood it as if they had made the latest beta RTM, so it is no longer beta, but I agree they could be much more clear in the description. Will try 9745 later today and report if it is working for me.

**Comment by radioactivetoy** [comment]
I have just been testing 9745-alpine and in my setup seems to work flawlessly.

**Comment by siomiz** [comment]
Great to hear, I'll promote it to latest soon...

**Comment by paskal** [comment]
This can be safely resolved I assume.

**Comment by radioactivetoy** [comment]
Closed. Thanks!
